services:
  frontend:
    build: ../../frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8081
    depends_on:
      - backend

  backend:
    build: ../../backend
    ports:
      - "8081:8081"
    env_file:
      - ../../backend/.env  # 确保相对路径正确，指向 backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      retries: 3
