apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ssr-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: my-next-frontend-ssr:latest
          ports:
            - containerPort: 3000
